{{- if .Values.backend.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maic-ui-backend-pvc
  labels:
    app.kubernetes.io/name: maic-ui
    app.kubernetes.io/component: backend
spec:
  accessModes:
    - {{ .Values.backend.persistence.accessMode }}
  {{- if .Values.backend.persistence.storageClass }}
  storageClassName: {{ .Values.backend.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size }}
{{- end }}
