apiVersion: v1
kind: Service
metadata:
  name: maic-ui-backend
  labels:
    app.kubernetes.io/name: maic-ui
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: maic-ui
    app.kubernetes.io/component: backend
