'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

export type Language = 'zh' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string, params?: Record<string, number | string>) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translation dictionary
const translations: Record<Language, Record<string, string>> = {
  zh: {
    // Dashboard
    'dashboard.title': 'MAIC-UI',
    'dashboard.studio': 'Studio',
    'dashboard.interactive_resource': '交互资源生成',
    'dashboard.template_library': '模板库',
    'dashboard.view_public_docs': '查看公开文档',
    'dashboard.total_docs': '总文档',
    'dashboard.completed': '已完成',
    'dashboard.processing': '处理中',
    'dashboard.quick_access': '快捷入口',
    'dashboard.create_resource': '创建资源',
    'dashboard.my_documents': '我的文档',
    'dashboard.recent_docs': '最近文档',
    'dashboard.no_docs': '暂无文档',
    'dashboard.ready': '已就绪',
    'dashboard.processing_status': '处理中',
    'dashboard.error_status': '异常',
    'dashboard.ai_model': 'AI模型',
    'dashboard.login_info': '登录信息',
    'dashboard.logout': '退出',
    'dashboard.user': '用户',
    'dashboard.not_logged_in': '未登录',
    'dashboard.loading': '数据加载中...',
    'dashboard.welcome': '欢迎来到MAIC-UI',
    'dashboard.select_method': '请选择生成方式，开始创建独属于你的交互学习界面',
    'dashboard.upload_pdf': '上传PDF',
    'dashboard.from_material': '从教材/资料生成',
    'dashboard.upload_ppt': '上传PPT',
    'dashboard.from_presentation': '从演示文稿生成',
    'dashboard.input_concept': '输入知识点',
    'dashboard.custom_generate': '自定义生成内容',
    'dashboard.show_all': '展示所有文档',
    'dashboard.collapse': '收起',
    'dashboard.error_prefix': '错误：',
    'dashboard.fetch_failed': '获取文档失败',
    'dashboard.language': '语言',

    // Model descriptions
    'model.glm47': 'GLM-4.7',
    'model.glm47_desc': '智谱最新模型，效果更佳',
    'model.glm46': 'GLM-4.6',
    'model.glm46_desc': '智谱稳定模型，并发受限时可切换',
    'model.opus46': 'Claude Opus 4.6',
    'model.opus46_desc': 'Anthropic最强模型',
    'model.sonnet46': 'Claude Sonnet 4.6',
    'model.sonnet46_desc': 'Anthropic均衡模型',
    'model.haiku45': 'Claude Haiku 4.5',
    'model.haiku45_desc': 'Anthropic轻量快速模型',
    'model.gemini25_flash': 'Gemini 2.5 Flash',
    'model.gemini25_flash_desc': 'Google 最新多模态模型，极速响应与强推理',
    'model.gemini20_flash': 'Gemini 2.0 Flash',
    'model.gemini20_flash_desc': 'Google 旗舰高速多模态模型',
    'model.gemini15_pro': 'Gemini 1.5 Pro',
    'model.gemini15_pro_desc': 'Google 深度推理与超长上下文模型',
    'model.gemini15_flash': 'Gemini 1.5 Flash',
    'model.gemini15_flash_desc': 'Google 经济快速的多模态模型',

    // Upload forms - common
    'upload.select_method': '选择创建方式',
    'upload.upload_file': '上传文件',
    'upload.drag_or_click': '拖拽或点击上传',
    'upload.support_pdf': '支持 PDF（≤50MB）',
    'upload.support_pdf_pptx': '支持 PDF、PPTX（≤50MB）',
    'upload.example_pdf': '示例：数学课件.pdf',
    'upload.example_pptx': '示例：教学演示稿.pptx',
    'upload.select_file': '选择文件',
    'upload.replace': '替换',
    'upload.delete': '删除',
    'upload.basic_settings': '基础设置',
    'upload.title': '标题',
    'upload.title_placeholder': '请输入文档标题',
    'upload.title_placeholder_ppt': '请输入演示文稿标题',
    'upload.grade': '年级',
    'upload.select_grade': '选择年级',
    'upload.subject': '科目',
    'upload.subject_placeholder': '例如：数学、科学、历史',
    'upload.subject_placeholder_ppt': '例如：数学、物理、化学',
    'upload.advanced_settings': '进阶设置（点击展开）',
    'upload.interests': '学习兴趣',
    'upload.interests_placeholder': '例如：太空, 动物, 科技（逗号分隔）',
    'upload.description': '描述',
    'upload.description_placeholder': '描述您的个性化需求',
    'upload.description_placeholder_ppt': '演示文稿内容的简要描述',
    'upload.make_public': '设为公开文档（任何人可以查看）',
    'upload.make_public_ppt': '设为公开演示文稿（任何人都可以查看）',
    'upload.auto_open': '自动在新标签页中打开结果',
    'upload.include_exercises': '生成习题（测验/练习）',
    'upload.include_prerequisites': '生成前置知识点',
    'upload.configure_options': '配置处理选项（选择批次大小或指定页面）',
    'upload.generation_mode': '生成模式',
    'upload.fast_mode': '快速生成',
    'upload.fast_mode_desc': '3-5分钟，适合预览',
    'upload.heavy_mode': '高质量生成',
    'upload.heavy_mode_desc': '10-15分钟，更精美 + 交互',
    'upload.recommended': '推荐',
    'upload.processing': '处理中...',
    'upload.generating': '生成中...',
    'upload.generate_button': '一键生成教学资源',
    'upload.next_steps': '接下来会发生什么：',
    'upload.next_steps_desc': 'AI 将分析您的演示文稿内容，并自动为需要视觉说明的概念生成交互式页面，处理可能需要几分钟',
    'upload.tip': '提示：',
    'upload.tip_desc': '系统会根据你输入的知识点与设计思路生成交互式学习界面，处理通常需要几分钟',
    'upload.upload_success': '上传成功：',
    'upload.uploaded_processing': '已上传：',
    'upload.uploaded_processing_desc': '，系统正在处理中',
    'upload.error_pdf_only': '请仅上传 PDF 文件',
    'upload.error_pdf_pptx_only': '请上传 PDF 或 PPTX 文件',
    'upload.error_upload_first': '请先上传 PDF 文件',
    'upload.error_select_first': '请先选择文件',
    'upload.error_fill_title': '请填写文档标题',
    'upload.error_fill_title_ppt': '请填写标题',
    'upload.error_login': '需要先登录后再上传',
    'upload.error_login_submit': '需要先登录后再提交',
    'upload.error_upload_failed': '上传失败，请稍后重试',
    'upload.error_submit_failed': '提交失败，请稍后重试',
    'upload.upload_failed': '上传失败：',
    'upload.submit_failed': '上传失败：',

    // Concept form
    'concept.subject': '科目 *',
    'concept.subject_placeholder': '例如：物理、数学、化学',
    'concept.name': '知识点名称 *',
    'concept.name_placeholder': '例如：声音的三要素',
    'concept.overview': '知识点概述 *',
    'concept.overview_placeholder': '简要描述这个知识点的核心内容',
    'concept.mastery_points': '学生掌握要点 *',
    'concept.mastery_points_placeholder': '列出学生需要掌握的问题或要点',
    'concept.design_idea': '组件设计思路 *',
    'concept.design_idea_placeholder': '说明你希望的交互组件形式与学习过程',
    'concept.grade': '年级',
    'concept.interests': '学习兴趣',
    'concept.interests_placeholder': '例如：太空、动物、科技',
    'concept.custom_needs': '个性化需求',
    'concept.custom_needs_placeholder': '描述你的特殊要求或希望强化的方向',
    'concept.error_subject': '请输入科目',
    'concept.error_name': '请输入知识点名称',
    'concept.error_overview': '请输入知识点概述',
    'concept.error_mastery': '请输入学生掌握要点',
    'concept.error_design': '请输入组件设计思路',
    'concept.submit_success': '知识点',

    // Grade levels
    'grade.kindergarten': '幼儿园',
    'grade.grade1': '小学一年级',
    'grade.grade2': '小学二年级',
    'grade.grade3': '小学三年级',
    'grade.grade4': '小学四年级',
    'grade.grade5': '小学五年级',
    'grade.grade6': '小学六年级',
    'grade.grade7': '初中一年级',
    'grade.grade8': '初中二年级',
    'grade.grade9': '初中三年级',
    'grade.grade10': '高中一年级',
    'grade.grade11': '高中二年级',
    'grade.grade12': '高中三年级',
    'grade.college': '本科',
    'grade.graduate': '研究生',

    // Login page
    'login.title': '登录',
    'login.subtitle': '登录到 MAIC-UI',
    'login.username': '用户名',
    'login.username_placeholder': '请输入用户名',
    'login.password': '密码',
    'login.password_placeholder': '请输入密码',
    'login.submit': '登录',
    'login.register_link': '还没有账户？注册',
    'login.error_credentials': '用户名或密码错误',
    'login.error_generic': '登录失败，请稍后重试',

    // Register page
    'register.title': '注册',
    'register.subtitle': '创建 MAIC-UI 账户',
    'register.username': '用户名',
    'register.username_placeholder': '请输入用户名',
    'register.email': '邮箱',
    'register.email_placeholder': '请输入邮箱',
    'register.password': '密码',
    'register.password_placeholder': '请输入密码',
    'register.full_name': '姓名',
    'register.full_name_placeholder': '请输入姓名（可选）',
    'register.submit': '注册',
    'register.login_link': '已有账户？登录',
    'register.success': '注册成功！正在跳转到登录页面...',
    'register.error_generic': '注册失败，请稍后重试',

    // Templates page
    'templates.title': '模板库',
    'templates.subtitle': '浏览和预览模板',
    'templates.preview': '预览',
    'templates.use_template': '使用模板',
    'templates.no_templates': '暂无模板',
    'templates.library': '模板库',
    'templates.library_desc': '浏览和选择预构建模板来加速内容生成',
    'templates.workflow_type': '工作流类型',
    'templates.category': '类别',
    'templates.complexity': '复杂度',
    'templates.all': '全部',
    'templates.simple': '简单',
    'templates.medium': '中等',
    'templates.complex': '复杂',
    'templates.unknown': '未知',
    'templates.ppt_demo': 'PPT演示',
    'templates.website_pdf': 'PDF转网页',
    'templates.website_concept': '概念讲解',
    'templates.reset_filter': '重置筛选',
    'templates.load_failed': '加载模板失败',
    'templates.found_count': '找到 {count} 个模板',
    'templates.no_match': '没有找到匹配的模板',
    'templates.adjust_filter': '请尝试调整筛选条件',
    'templates.public': '公开',
    'templates.template': '模板',
    'templates.type': '类型',
    'templates.subject': '学科',
    'templates.usage_count': '使用次数',

    // Public documents page
    'public.title': '公开文档',
    'public.subtitle': '浏览公开的学习资源',
    'public.search_placeholder': '搜索文档...',
    'public.no_docs': '暂无公开文档',
    'public.view': '查看',
    'public.by': '创建者：',
    'public.pages': '页数：',

    // Navigation
    'nav.dashboard': '交互资源生成',
    'nav.ppt_upload': '上传PPT',
    'nav.templates': '模板库',
    'nav.public_docs': '查看公开文档',
    'nav.welcome': '欢迎，',
    'nav.logout': '退出登录',
    'nav.ai_model': 'AI模型:',
    'nav.zhipu': '智谱',
    'nav.zhipu_group': 'Zhipu AI (智谱)',
    'nav.anthropic': 'Anthropic (Claude)',
    'nav.language': '语言',

    // Public document viewer
    'public_doc.loading': '加载中...',
    'public_doc.error': '错误：',
    'public_doc.not_found': '未找到文档',
    'public_doc.invalid_id': '无效的文档ID',
    'public_doc.course_info': '课件信息',
    'public_doc.subject': '科目',
    'public_doc.not_specified': '未指定',
    'public_doc.grade': '年级',
    'public_doc.grade_suffix': '年级',
    'public_doc.knowledge_point': '知识点',
    'public_doc.pages': '页数',
    'public_doc.teaching_content': '教学内容',
    'public_doc.concept_overview': '知识点概述',
    'public_doc.learning_objectives': '学习目标',
    'public_doc.teaching_approach': '教学思路',
    'public_doc.generated_complete': '你的互动课件已生成完毕！',
    'public_doc.new_experience': '一个全新的互动学习体验已生成',
    'public_doc.ready': 'Ready',
    'public_doc.edit_processing': '编辑应用中',
    'public_doc.edit_completed': '编辑已完成',
    'public_doc.start_learning': '开始学习',
    'public_doc.download_course': '下载课件',
    'public_doc.download_pdf': '下载PDF',
    'public_doc.return_results': '返回结果页',
    'public_doc.version_section': '版本板块',
    'public_doc.interactive_versions': '可交互文件版本',
    'public_doc.no_versions': '暂无可用版本',
    'public_doc.preview_section': '课件预览',
    'public_doc.preview_desc': '快速看一下你生成的互动课件长什么样',
    'public_doc.analysis_section': '内容分析板块',
    'public_doc.main_topics': '主要主题',
    'public_doc.prerequisite': '前置知识点',
    'public_doc.interactive_section': '交互板块',
    'public_doc.check_answer': '检查答案',
    'public_doc.try_again': '再试一次',
    'public_doc.processing_doc': '正在处理文档',
    'public_doc.processing_desc': '系统正在分析内容并生成互动课件，请稍候',
    'public_doc.process_failed': '处理失败',
    'public_doc.unknown_error': '处理过程中发生未知错误',
    'public_doc.interactive_site': '交互式学习网站',
    'public_doc.download_failed': '下载失败，请稍后重试',
    'public_doc.no_html': '该文档没有可下载的网页文件',
    'public_doc.fetch_version_failed': '获取版本内容失败',
    'public_doc.set_current_failed': '设置当前版本失败',
    'public_doc.delete_failed': '删除失败',
    'public_doc.invalid_version_id': '无效的版本ID',
    'public_doc.no_modification': '无修改指令',

    // Version list table
    'version.title': '版本',
    'version.date': '修改日期',
    'version.instruction': '修改指令',
    'version.action': '操作',
    'version.current': '当前使用',
    'version.apply': '应用',
    'version.delete': '删除',
    'version.no_prompt': '初始版本',
    'version.default_label': '可交互文件版本',
    'version.root_cannot_delete': '初始版本不可删除',
  },
  en: {
    // Dashboard
    'dashboard.title': 'MAIC-UI',
    'dashboard.studio': 'Studio',
    'dashboard.interactive_resource': 'Interactive Resource',
    'dashboard.template_library': 'Template Library',
    'dashboard.view_public_docs': 'View Public Documents',
    'dashboard.total_docs': 'Total',
    'dashboard.completed': 'Completed',
    'dashboard.processing': 'Processing',
    'dashboard.quick_access': 'Quick Access',
    'dashboard.create_resource': 'Create Resource',
    'dashboard.my_documents': 'My Documents',
    'dashboard.recent_docs': 'Recent Documents',
    'dashboard.no_docs': 'No documents',
    'dashboard.ready': 'Ready',
    'dashboard.processing_status': 'Processing',
    'dashboard.error_status': 'Error',
    'dashboard.ai_model': 'AI Model',
    'dashboard.login_info': 'Login Info',
    'dashboard.logout': 'Logout',
    'dashboard.user': 'User',
    'dashboard.not_logged_in': 'Not logged in',
    'dashboard.loading': 'Loading data...',
    'dashboard.welcome': 'Welcome to MAIC-UI',
    'dashboard.select_method': 'Select a generation method to create your interactive learning interface',
    'dashboard.upload_pdf': 'Upload PDF',
    'dashboard.from_material': 'Generate from materials',
    'dashboard.upload_ppt': 'Upload PPT',
    'dashboard.from_presentation': 'Generate from presentation',
    'dashboard.input_concept': 'Input Concept',
    'dashboard.custom_generate': 'Custom generation',
    'dashboard.show_all': 'Show All Documents',
    'dashboard.collapse': 'Collapse',
    'dashboard.error_prefix': 'Error: ',
    'dashboard.fetch_failed': 'Failed to fetch documents',
    'dashboard.language': 'Language',

    // Model descriptions
    'model.glm47': 'GLM-4.7',
    'model.glm47_desc': 'Zhipu latest model, better results',
    'model.glm46': 'GLM-4.6',
    'model.glm46_desc': 'Zhipu stable model, switch when limited',
    'model.opus46': 'Claude Opus 4.6',
    'model.opus46_desc': 'Anthropic most powerful model',
    'model.sonnet46': 'Claude Sonnet 4.6',
    'model.sonnet46_desc': 'Anthropic balanced model',
    'model.haiku45': 'Claude Haiku 4.5',
    'model.haiku45_desc': 'Anthropic lightweight fast model',
    'model.gemini25_flash': 'Gemini 2.5 Flash',
    'model.gemini25_flash_desc': 'Google latest multimodal model with fast reasoning',
    'model.gemini20_flash': 'Gemini 2.0 Flash',
    'model.gemini20_flash_desc': 'Google flagship high-speed multimodal model',
    'model.gemini15_pro': 'Gemini 1.5 Pro',
    'model.gemini15_pro_desc': 'Google deep reasoning & long-context model',
    'model.gemini15_flash': 'Gemini 1.5 Flash',
    'model.gemini15_flash_desc': 'Google lightweight fast multimodal model',

    // Upload forms - common
    'upload.select_method': 'Select Creation Method',
    'upload.upload_file': 'Upload File',
    'upload.drag_or_click': 'Drag and drop or click to upload',
    'upload.support_pdf': 'Supports PDF (≤50MB)',
    'upload.support_pdf_pptx': 'Supports PDF, PPTX (≤50MB)',
    'upload.example_pdf': 'Example: Math lesson.pdf',
    'upload.example_pptx': 'Example: Teaching slides.pptx',
    'upload.select_file': 'Select File',
    'upload.replace': 'Replace',
    'upload.delete': 'Delete',
    'upload.basic_settings': 'Basic Settings',
    'upload.title': 'Title',
    'upload.title_placeholder': 'Enter document title',
    'upload.title_placeholder_ppt': 'Enter presentation title',
    'upload.grade': 'Grade',
    'upload.select_grade': 'Select grade',
    'upload.subject': 'Subject',
    'upload.subject_placeholder': 'e.g., Math, Science, History',
    'upload.subject_placeholder_ppt': 'e.g., Math, Physics, Chemistry',
    'upload.advanced_settings': 'Advanced Settings (click to expand)',
    'upload.interests': 'Learning Interests',
    'upload.interests_placeholder': 'e.g., Space, Animals, Technology (comma separated)',
    'upload.description': 'Description',
    'upload.description_placeholder': 'Describe your personalization needs',
    'upload.description_placeholder_ppt': 'Brief description of presentation content',
    'upload.make_public': 'Make public (anyone can view)',
    'upload.make_public_ppt': 'Make presentation public (anyone can view)',
    'upload.auto_open': 'Auto-open result in new tab',
    'upload.include_exercises': 'Generate exercises (quizzes/practice)',
    'upload.include_prerequisites': 'Generate prerequisite knowledge',
    'upload.configure_options': 'Configure processing options (select batch size or pages)',
    'upload.generation_mode': 'Generation Mode',
    'upload.fast_mode': 'Fast Generation',
    'upload.fast_mode_desc': '3-5 min, suitable for preview',
    'upload.heavy_mode': 'High Quality Generation',
    'upload.heavy_mode_desc': '10-15 min, more polished + interactive',
    'upload.recommended': 'Recommended',
    'upload.processing': 'Processing...',
    'upload.generating': 'Generating...',
    'upload.generate_button': 'Generate Learning Resources',
    'upload.next_steps': 'What happens next:',
    'upload.next_steps_desc': 'AI will analyze your presentation content and automatically generate interactive pages for concepts that need visual explanation. Processing may take a few minutes.',
    'upload.tip': 'Tip:',
    'upload.tip_desc': 'The system will generate an interactive learning interface based on your input concept and design ideas. Processing usually takes a few minutes.',
    'upload.upload_success': 'Upload successful: ',
    'upload.uploaded_processing': 'Uploaded: ',
    'upload.uploaded_processing_desc': ', system is processing',
    'upload.error_pdf_only': 'Please upload only PDF files',
    'upload.error_pdf_pptx_only': 'Please upload PDF or PPTX files',
    'upload.error_upload_first': 'Please upload a PDF file first',
    'upload.error_select_first': 'Please select a file first',
    'upload.error_fill_title': 'Please enter document title',
    'upload.error_fill_title_ppt': 'Please enter title',
    'upload.error_login': 'Please login first to upload',
    'upload.error_login_submit': 'Please login first to submit',
    'upload.error_upload_failed': 'Upload failed, please try again later',
    'upload.error_submit_failed': 'Submit failed, please try again later',
    'upload.upload_failed': 'Upload failed: ',
    'upload.submit_failed': 'Upload failed: ',

    // Concept form
    'concept.subject': 'Subject *',
    'concept.subject_placeholder': 'e.g., Physics, Math, Chemistry',
    'concept.name': 'Concept Name *',
    'concept.name_placeholder': 'e.g., Three Elements of Sound',
    'concept.overview': 'Concept Overview *',
    'concept.overview_placeholder': 'Briefly describe the core content of this concept',
    'concept.mastery_points': 'Mastery Points *',
    'concept.mastery_points_placeholder': 'List the questions or points students need to master',
    'concept.design_idea': 'Component Design Ideas *',
    'concept.design_idea_placeholder': 'Describe the interactive component form and learning process you want',
    'concept.grade': 'Grade',
    'concept.interests': 'Learning Interests',
    'concept.interests_placeholder': 'e.g., Space, Animals, Technology',
    'concept.custom_needs': 'Custom Needs',
    'concept.custom_needs_placeholder': 'Describe your special requirements or directions to emphasize',
    'concept.error_subject': 'Please enter subject',
    'concept.error_name': 'Please enter concept name',
    'concept.error_overview': 'Please enter concept overview',
    'concept.error_mastery': 'Please enter mastery points',
    'concept.error_design': 'Please enter component design ideas',
    'concept.submit_success': 'Concept',

    // Grade levels
    'grade.kindergarten': 'Kindergarten',
    'grade.grade1': '1st Grade',
    'grade.grade2': '2nd Grade',
    'grade.grade3': '3rd Grade',
    'grade.grade4': '4th Grade',
    'grade.grade5': '5th Grade',
    'grade.grade6': '6th Grade',
    'grade.grade7': '7th Grade (Middle School)',
    'grade.grade8': '8th Grade (Middle School)',
    'grade.grade9': '9th Grade (Middle School)',
    'grade.grade10': '10th Grade (High School)',
    'grade.grade11': '11th Grade (High School)',
    'grade.grade12': '12th Grade (High School)',
    'grade.college': 'College',
    'grade.graduate': 'Graduate',

    // Login page
    'login.title': 'Login',
    'login.subtitle': 'Login to MAIC-UI',
    'login.username': 'Username',
    'login.username_placeholder': 'Enter username',
    'login.password': 'Password',
    'login.password_placeholder': 'Enter password',
    'login.submit': 'Login',
    'login.register_link': 'No account? Register',
    'login.error_credentials': 'Invalid username or password',
    'login.error_generic': 'Login failed, please try again later',

    // Register page
    'register.title': 'Register',
    'register.subtitle': 'Create MAIC-UI Account',
    'register.username': 'Username',
    'register.username_placeholder': 'Enter username',
    'register.email': 'Email',
    'register.email_placeholder': 'Enter email',
    'register.password': 'Password',
    'register.password_placeholder': 'Enter password',
    'register.full_name': 'Full Name',
    'register.full_name_placeholder': 'Enter full name (optional)',
    'register.submit': 'Register',
    'register.login_link': 'Have an account? Login',
    'register.success': 'Registration successful! Redirecting to login...',
    'register.error_generic': 'Registration failed, please try again later',

    // Templates page
    'templates.title': 'Template Library',
    'templates.subtitle': 'Browse and preview templates',
    'templates.preview': 'Preview',
    'templates.use_template': 'Use Template',
    'templates.no_templates': 'No templates available',
    'templates.library': 'Template Library',
    'templates.library_desc': 'Browse and select pre-built templates to accelerate content generation',
    'templates.workflow_type': 'Workflow Type',
    'templates.category': 'Category',
    'templates.complexity': 'Complexity',
    'templates.all': 'All',
    'templates.simple': 'Simple',
    'templates.medium': 'Medium',
    'templates.complex': 'Complex',
    'templates.unknown': 'Unknown',
    'templates.ppt_demo': 'PPT Demo',
    'templates.website_pdf': 'PDF to Web',
    'templates.website_concept': 'Concept Teaching',
    'templates.reset_filter': 'Reset Filters',
    'templates.load_failed': 'Failed to load templates',
    'templates.found_count': 'Found {count} templates',
    'templates.no_match': 'No matching templates found',
    'templates.adjust_filter': 'Try adjusting your filters',
    'templates.public': 'Public',
    'templates.template': 'Template',
    'templates.type': 'Type',
    'templates.subject': 'Subject',
    'templates.usage_count': 'Usage',

    // Public documents page
    'public.title': 'Public Documents',
    'public.subtitle': 'Browse public learning resources',
    'public.search_placeholder': 'Search documents...',
    'public.no_docs': 'No public documents',
    'public.view': 'View',
    'public.by': 'Created by: ',
    'public.pages': 'Pages: ',

    // Navigation
    'nav.dashboard': 'Interactive Resource',
    'nav.ppt_upload': 'Upload PPT',
    'nav.templates': 'Template Library',
    'nav.public_docs': 'Public Documents',
    'nav.welcome': 'Welcome, ',
    'nav.logout': 'Logout',
    'nav.ai_model': 'AI Model:',
    'nav.zhipu': 'Zhipu',
    'nav.zhipu_group': 'Zhipu AI',
    'nav.anthropic': 'Anthropic (Claude)',
    'nav.language': 'Language',

    // Public document viewer
    'public_doc.loading': 'Loading...',
    'public_doc.error': 'Error: ',
    'public_doc.not_found': 'Document not found',
    'public_doc.invalid_id': 'Invalid document ID',
    'public_doc.course_info': 'Course Info',
    'public_doc.subject': 'Subject',
    'public_doc.not_specified': 'Not specified',
    'public_doc.grade': 'Grade',
    'public_doc.grade_suffix': ' Grade',
    'public_doc.knowledge_point': 'Concept',
    'public_doc.pages': 'Pages',
    'public_doc.teaching_content': 'Teaching Content',
    'public_doc.concept_overview': 'Concept Overview',
    'public_doc.learning_objectives': 'Learning Objectives',
    'public_doc.teaching_approach': 'Teaching Approach',
    'public_doc.generated_complete': 'Your interactive course is ready!',
    'public_doc.new_experience': 'A new interactive learning experience has been generated',
    'public_doc.ready': 'Ready',
    'public_doc.edit_processing': 'Edit processing',
    'public_doc.edit_completed': 'Edit completed',
    'public_doc.start_learning': 'Start Learning',
    'public_doc.download_course': 'Download Course',
    'public_doc.download_pdf': 'Download PDF',
    'public_doc.return_results': 'Return to Results',
    'public_doc.version_section': 'Version Section',
    'public_doc.interactive_versions': 'Interactive file versions',
    'public_doc.no_versions': 'No available versions',
    'public_doc.preview_section': 'Course Preview',
    'public_doc.preview_desc': 'Quick preview of your generated interactive course',
    'public_doc.analysis_section': 'Content Analysis',
    'public_doc.main_topics': 'Main Topics',
    'public_doc.prerequisite': 'Prerequisite Knowledge',
    'public_doc.interactive_section': 'Interactive Section',
    'public_doc.check_answer': 'Check Answer',
    'public_doc.try_again': 'Try Again',
    'public_doc.processing_doc': 'Processing document',
    'public_doc.processing_desc': 'System is analyzing content and generating interactive course, please wait',
    'public_doc.process_failed': 'Processing failed',
    'public_doc.unknown_error': 'Unknown error occurred during processing',
    'public_doc.interactive_site': 'Interactive Learning Site',
    'public_doc.download_failed': 'Download failed, please try again later',
    'public_doc.no_html': 'This document has no downloadable HTML file',
    'public_doc.fetch_version_failed': 'Failed to fetch version content',
    'public_doc.set_current_failed': 'Failed to set current version',
    'public_doc.delete_failed': 'Delete failed',
    'public_doc.invalid_version_id': 'Invalid version ID',
    'public_doc.no_modification': 'No modification instruction',

    // Version list table
    'version.title': 'Version',
    'version.date': 'Date Modified',
    'version.instruction': 'Instruction',
    'version.action': 'Actions',
    'version.current': 'Current',
    'version.apply': 'Apply',
    'version.delete': 'Delete',
    'version.no_prompt': 'Initial version',
    'version.default_label': 'Interactive File Versions',
    'version.root_cannot_delete': 'Initial version cannot be deleted',
  }
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en')

  // Load saved language preference from localStorage on mount
  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language | null
    if (savedLang && (savedLang === 'zh' || savedLang === 'en')) {
      setLanguageState(savedLang)
    } else {
      setLanguageState('en')
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string, params?: Record<string, number | string>): string => {
    let text = translations[language][key] || key
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v))
      })
    }
    return text
  }

  const value: LanguageContextType = {
    language,
    setLanguage,
    t,
  }

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}